name: MEOWT Moderator Bot

on:
  schedule:
    - cron: "*/2 * * * *"    # every 2 minutes
  workflow_dispatch:

jobs:
  moderate:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install deps
        run: npm ci

      - name: Verify deps
        run: npm ls --depth=0

      - name: Configure GCP creds (service account JSON)
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Run moderator
        env:
          RPC_URL:             ${{ secrets.RPC_URL }}
          GAME_ADDRESS:        ${{ secrets.GAME_ADDRESS }}
          BOT_PRIVATE_KEY:     ${{ secrets.BOT_PRIVATE_KEY }}
          # OPENAI_API_KEY (if your script uses it)
          OPENAI_API_KEY:      ${{ secrets.OPENAI_API_KEY }}
        run: node moderator.mjs
